config/routes.rb
Rails.application.routes.draw do
  resources :friends
  devise_for :users
  resources :songs
  resources :tapes

  root 'tapes#index'

  get 'share'=> 'tapes#share'
  

end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :tape

	has_attached_file :audio
	validates_attachment_presence :audio
	validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg', 'audio/m4a']
end

app/models/tape.rb
class Tape < ActiveRecord::Base
	has_many :songs
	belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :tapes 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.


  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :name, :password, :password_confirmation) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :name, :password, :password_confirmation, :current_password) }

  end
 end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        UserMailer.tape_email(@friend).deliver_now
        format.html { redirect_to @friend, notice: 'Your tape was successfully sent!' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Your tape was sent successfully!' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:name, :email, :tape_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song.tape, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to tape_path(id: @song.tape_id), notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :artist, :tape_id, :audio)
    end
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  before_action :set_tape, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 
  # GET /tapes
  # GET /tapes.json
  def index
    @tapes = Tape.where(user_id: current_user.id)
  end

  def share
    @tape = Tape.find(params[:id])
    @friend = Friend.new
  end
  # GET /tapes/1
  # GET /tapes/1.json
  def show
    @song = Song.new 
  end

  # GET /tapes/new
  def new
    @tape = Tape.new
  end

  # GET /tapes/1/edit
  def edit
  end

  # POST /tapes
  # POST /tapes.json
  def create
    @tape = Tape.new(tape_params)

    respond_to do |format|
      if @tape.save
        format.html { redirect_to root_path, notice: 'Tape was created. Now add some tracks!' }
        format.json { render :show, status: :created, location: @tape }
      else
        format.html { render :new }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tapes/1
  # PATCH/PUT /tapes/1.json
  def update
    respond_to do |format|
      if @tape.update(tape_params)
        format.html { redirect_to @tape, notice: 'Tape was successfully remixed.' }
        format.json { render :show, status: :ok, location: @tape }
      else
        format.html { render :edit }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tapes/1
  # DELETE /tapes/1.json
  def destroy
    @tape.destroy
    respond_to do |format|
      format.html { redirect_to tapes_url, notice: 'Tape has been stomped on and thrown away.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tape
      @tape = Tape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tape_params
      params.require(:tape).permit(:title, :friend, :note, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder: "Friend's Name" %>
  </div><br/>
  <div class="field">
    <%= f.text_field :email, placeholder: "Friend's Email" %>
  </div><br/>
  <div class="field">
    <%= f.hidden_field :tape_id, value: @tape.id %>
  </div>
  <div class="actions">
    <%= f.submit "Send", class: "btn btn-sm btn-warning" %>
  </div><br/>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Friends</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tape</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.tape_id %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Tape:</strong>
  <%= @friend.tape_id %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tapetrack</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>


  <body class="background">
    <div class="image-background">
      <center><%= image_tag("cassetteplayer.png") %></center>
    </div>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Collection", root_path, class: "navbar-brand"%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Create Tape", new_tape_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <%else%>
              <li><%= link_to "Sign In", new_user_session_path%></li>
              <li><%= link_to "Sign Up", new_user_registration_path%></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

      <div class="container">
      <%= yield %>
      </div>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "Name"%>
  </div>
  <!-- <div class="field">
    <%#= f.label :artist %><br>
    <%#= f.text_field :artist %>
  </div> -->
  <div class="field cant-see-me">
    <%= f.number_field :tape_id, value: @tape.id %>
  </div>
  <div class="field">
    <%= f.label "Upload" %><br>
    <%= f.file_field :audio %>
  </div><br/>

  <div class="actions">
    <%= f.submit "Add", class: "btn btn-sm btn-warning"%>
  </div><br/>
<% end %>

<p>
<%= link_to "Done", root_path, class: "btn btn-sm btn-warning"%>
</p>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.artist %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/tapes/_form.html.erb
<%= form_for(@tape) do |f| %>
  <% if @tape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tape.errors.count, "error") %> prohibited this tape from being saved:</h2>

      <ul>
      <% @tape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
      <div class="col-md-4">
      </div>
    <center>
      <div class="col-md-4">
        <div class="panel panel-default panel-two">
            <p class="tape_name">Create A Tape</p>
            <div class="field">
              <%= f.text_field :title, placeholder: "Tape Title" %>
            </div><br/>
            <div class="field">
              <%= f.text_area :note, placeholder: "Send a note with your tape" %>
            </div><br/>
            <div class="field">
              <%= f.hidden_field :user_id, value: current_user.id %>
            </div>
            <div class=>
              <%= image_tag("blacktape.png") %>
            </div><br/>
            <div class="actions">
              <%= f.submit "Create", class: "btn btn-sm btn-warning"%>
            </div><br/>
        </div>
      </div>
    </center>
  </div>

<% end %>

app/views/tapes/edit.html.erb
<h1>Editing Tape</h1>

<%= render 'form' %>

<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/index.html.erb
<p id="notice"><%= notice %></p>
  <% if user_signed_in? %>
    <h4> <%= current_user.name %>'s collection</h4>
  <% end %>

  <% if user_signed_in? %>
    <div class = "row">
      <% @tapes.each do |tape| %>
        <div class="col-md-3">
          <div class = "panel panel-sm">
            <h6><%= tape.title %></h6>
              <%= image_tag ('blacktape.png')%>
            <div class = "panel-body, float-left">
              <%= link_to '', tape, class: "glyphicon glyphicon-music btn btn-sm btn-warning"%>
              <%= link_to '', share_path(id: tape.id), class: "glyphicon glyphicon-share btn btn-sm btn-warning"%>
              <%= link_to '', tape, class: "glyphicon glyphicon-remove btn btn-sm btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
              <a href="#" data-toggle="modal" data-target="#myModal_<%= tape.id%>">
                    <span class="glyphicon glyphicon-play btn btn-sm btn-warning"></span>
              </a>
            </div>          
          </div>
        </div>

          <!-- Modal -->
        <div class="modal fade" id="myModal_<%=tape.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-background" role="document">
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><br/><br/></br>
                  <center><h4 class="modal-title" id="myModalLabel"></h4></center>
                </div>
                <div class="modal-body">
                  <div class="container-fluid">
                    <% tape.songs.each do |song| %>
                      <div class="row">
                        <div class="col-md-5">
                          <ul>
                            <li><%= song.name %></li>
                          </ul>
                        </div>
                        <div class="col-md-7">
                          <audio controls <source src="<%= song.audio.url %>" type="audio/mpeg" />
                          </audio>
                        </div>
                      </div>
                    <%end%>
                  </div>
                </div>  
                <div class="modal-footer">
                  <div class="note">
                    <%= tape.note %>
                  </div>
                </div>
              </div>
            </div>
        </div>       
      <% end %>
    </div>
  <%else%>
    <p>Add Some Tapes</p>
  <% end %>

app/views/tapes/new.html.erb
<div class="new-tape">
<%= render 'form' %>
</div>

app/views/tapes/share.html.erb
<% if user_signed_in?%>
<h4>Share <%= @tape.title %> with a friend!</h4>
<%else%>
<h3>Create an account or sign in to create your own mix!</h3>
<%end%>
      
      <div class="col-md-3">
      </div>
      <div class="col-md-3">
        <div class = "panel">
            <a href="#" data-toggle="modal" data-target="#myModal_<%= @tape.id%>">
                <span class="glyphicon glyphicon-play btn btn-sm btn-warning"></span>
            </a>
          <div class = "panel-body, float-left">
            <%= image_tag ('blacktape.png')%>
          </div>          
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="col-md-3">
          <div class="panel panel-default panel-two"><br/>
            <center>
              <%= render 'friends/form'%>
            </center>
          </div>
       </div>
     <%end%>

       <!-- Modal -->
      <div class="modal fade" id="myModal_<%=@tape.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-background" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><br/><br/></br>
              <center><h4 class="modal-title" id="myModalLabel"></h4></center>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                    <% @tape.songs.each do |song| %>
                      <div class="row">
                      <div class="col-md-5 track_name">
                      <p><%= song.name %></p><!-- <button type="button" class= "glyphicon glyphicon-play"></button></p> -->
                      </div>
                      <div class="col-md-7">
                      <audio controls <source src="<%= song.audio.url %>" type="audio/mpeg" />
                      </audio>
                      </div>
                      </div>
                    <%end%>
              </div>
            </div>  
            <div class="modal-footer">
              <div class="note">
                <%= @tape.note %>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/tapes/show.html.erb
<h4>Add Some Tracks</h4><br/>

<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-4">
    <center>
      <div class="panel panel-default panel-two">
          <p class="tape_name"><%=@tape.title%>
          <%= link_to "", edit_tape_path, class: "glyphicon glyphicon-edit"%></p>
          <div>
          	<%= render 'songs/form' %>
          </div>
      </div>
    </center>
  </div>

  <div class="col-sm-4">
    <h3> Tracks </h3>
      <% @tape.songs.each do |song| %>
            <p class="track_name"><%= song.name %>
            <%= link_to '', song, class: "glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <%end%>
  </div>

</div>